#!/bin/bash
#$ -S /bin/bash
#$ -N hifi_02
#$ -cwd
#$ -q your.q
#$ -pe OpenMP 4
#$ -l s_vmem=64G
#$ -l h="!bad_node"
#$ -o logs/02/02-2.322samples.o.log
#$ -e logs/02/02-2.322samples.e.log
set -euo pipefail
source /path/to/HiFi-human-WGS-WDL-3.1.0/env.sh


CONF=cromwell.examples.edit.conf
CROMWELL=cromwell-86.jar

WDL=$1
INPUT_JSON=$2


java \
  -Xms2g \
  -Xmx16g \
  -XX:ActiveProcessorCount=4 \
  -Dconfig.file=$CONF \
  -jar $CROMWELL \
  run $WDL \
  --inputs $INPUT_JSON
