backend {
  default = "SGE"

  providers {
    SGE {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        concurrent-job-limit = 24

        root = "cromwell-executions"
        
		docker {
          hash-lookup = false
        }

        runtime-attributes = """
        Int cpu = 1
        Int memory
        String? sge_queue
        String? sge_project
        String? docker
        """

        submit = """
        qsub \
        -terse \
        -S /bin/bash \
        -N ${job_name} \
        -cwd \
        -o ${out}.qsub \
        -e ${err}.qsub \
        -pe OpenMP ${cpu} \
        -l s_vmem=${memory} \
        ${"-q " + sge_queue} \
        -l h="!centauri03" \
        ${script}
        """

        submit-docker = """
        echo "docker run --rm --user $(id -u):$(id -g) -v ${cwd}:${docker_cwd} ${docker} ${job_shell} ${docker_script}" | \
		qsub \
        -terse \
        -S /bin/bash \
        -N ${job_name} \
        -cwd \
        -o ${out}.qsub \
        -e ${err}.qsub \
        -pe OpenMP ${cpu} \
        -l s_vmem=${memory} \
        ${"-q " + sge_queue} \
        -l h="!centauri03" \
        """

        kill = "qdel ${job_id}"
        check-alive = "qstat -j ${job_id}"
        job-id-regex = "(\\d+)"

        filesystems {
          local {
            localization: ["hard-link", "soft-link", "copy"]
          }
        }
      }
    }
  }
}
